### ISSUE TITLE
Server errors in Extract

### ISSUE THREAD

**Issue by lnicola** [carllerche/tower-web#173]
I don't think there's a way to report server errors that occur during extraction. There is a `tower_web::extract::Error::web` function, but it's private.

This would be useful when doing e.g. IO (maybe looking up a session in a database), which can fail due to reasons outside of the client's control.

**Comment by manifest** [comment]
The `web` function is already public in the master [branch](https://github.com/carllerche/tower-web/blob/3d837646b4e32ad57b496a07d3c49db768d47290/src/extract/error.rs#L48), and with this [PR](https://github.com/carllerche/tower-web/pull/171) merged, we won't need `web` function since there will be `From<error::error::Error>` [implementation](https://github.com/carllerche/tower-web/blob/ad3f8f421cd85d0c4297e0357ab675b495abfee1/src/extract/error.rs#L66) for `extract:error::Error`.

**Comment by manifest** [comment]
There is [summary](https://github.com/carllerche/tower-web/issues/28#issuecomment-450699502) on changes the [PR](https://github.com/carllerche/tower-web/pull/171) introduce.

**Comment by lnicola** [comment]
Thanks, that seems nice. One question: should `internal_error` be public, too? It can be emulated with the same code (`Error::web(ErrorKind::internal().into())`), but might come in handy.

**Comment by manifest** [comment]
@lnicola the PR will make the following possible

```rust
Error::from(StatusCode::INTERNAL_SERVER_ERROR).into()
```
